import server from './index'
export const login = (param, config) => server.post('/login', param, config)
export const getInfo = (param, config) => server.get('/getUserInfo', param, config)
export const logout = (param, config) => server.get('/logout', param, config)
export const uploadPic = (param, config) => server.post('/uploadArticleHeadCover', param, config)
export const createBlog = (param, config) => server.post('/createArticle', param, config)
export const addTag = (param, config) => server.post('/addTag', param, config)
export const getAllTags = (param, config) => server.post('/getAllTags', param, config)
export const deleteTags = (param, config) => server.post('/deleteTags', param, config)
export const getArticleList = (param, config) => server.post('/getArticleList', param, config)
export const updateArticleById = (param, config) => server.post('/updateArticleById', param, config)
export const deleteArticlesById = (param, config) => server.post('/deleteArticleById', param, config)
export const secretArticle = (param, config) => server.post('/secretArticle', param, config)
